languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
baseurl = "https://aswinnatesh.github.io/resume/"
googleAnalytics = "UA-111383871-1"
theme = "hugo-vitae"


[params]
  author = "Aswin Natesh"
  title = "Aswin's Resume"
  description = ""
  avatar = "profile.jpg"
  email = " "
  email_full = "mailto:aswinnatesh.venkatesh@alumni.stonybrook.edu"
   email_full2 = "mailto:aswinnatesh.venkatesh@stonybrook.edu"
  website = "aswinnatesh.com"
  website_full = "https://aswinnatesh.github.io/"
  github = "aswinnatesh"
  twitter = "https://aswinnatesh.github.io/"
  tel = " "
  tel_full = " "
  google_maps = ""
  address = ""
  postcode = ""
  city = " San Jose, CA"
  country = ""

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
